/*
* nettols is a library for comonly used network stuff for windows and linux
* Copyright (C) 2017  TheCodingLab
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#pragma once

#include "defines.h"

#define ICMP_TYPE_ECHO_REPLY 0
#define ICMP_TYPE_RESERVED1 1
#define ICMP_TYPE_RESERVED2 2
#define ICMP_TYPE_DESTINATION_UNREACHABLE 3
#define ICMP_TYPE_SOURCE_QUENCH 4
#define ICMP_TYPE_REDIRECT 5
#define ICMP_TYPE_RESERVED3 6
#define ICMP_TYPE_RESERVED4 7
#define ICMP_TYPE_ECHO_REQUEST 8
#define ICMP_TYPE_ROUTER_ADVERTISEMENT 9
#define ICMP_TYPE_ROUTER_SOLICITATION 10
#define ICMP_TYPE_TIME_EXCEEDED 11
#define ICMP_TYPE_PARAMETER_PROBLEM 12
#define ICMP_TYPE_TIMESTAMP 13
#define ICMP_TYPE_TIMESTAMP_REPLY 14
#define ICMP_TYPE_INFORMATION_REQUEST 15
#define ICMP_TYPE_INFORMATION_REPLY 16
#define ICMP_TYPE_ADDRESS_MASK_REQUEST 18
#define ICMP_TYPE_ADDRESS_MASK_REPLY 18
#define ICMP_TYPE_RESERVED5 19
#define ICMP_TYPE_RESERVED6 20
#define ICMP_TYPE_RESERVED7 21
#define ICMP_TYPE_RESERVED8 22
#define ICMP_TYPE_RESERVED9 23
#define ICMP_TYPE_RESERVED10 24
#define ICMP_TYPE_RESERVED11 25
#define ICMP_TYPE_RESERVED12 26
#define ICMP_TYPE_RESERVED13 27
#define ICMP_TYPE_RESERVED14 28
#define ICMP_TYPE_RESERVED15 29
#define ICMP_TYPE_TRACEROUTE 30
#define ICMP_TYPE_DATAGRAM_CONVERSION_ERROR 31
#define ICMP_TYPE_MOBILE_HOST_REDIRECT 32
#define ICMP_TYPE_WHERE_ARE_YOU 33
#define ICMP_TYPE_I_AM_HERE 34
#define ICMP_TYPE_MOBILE_REGISTRATION_REQUEST 35
#define ICMP_TYPE_MOBILE_REGISTRATION_REPLY 36
#define ICMP_TYPE_DOMAIN_NAME_REQUEST 37
#define ICMP_TYPE_DOMAIN_NAME_REPLY 38
#define ICMP_TYPE_SKIP 39
#define ICMP_TYPE_PHOTURIS 40

// Type 0 (ICMP_TYPE_ECHO_REPLY)
#define ICMP_CODE_ECHO_REPLY 0
// Type 3 (ICMP_TYPE_DESTINATION_UNREACHABLE)
#define ICMP_CODE_DESTINATION_NETWORK_UNREACHABLE 0
#define ICMP_CODE_DESTINATION_HOST_UNREACHABLE 1
#define ICMP_CODE_DESTINATION_PROTOCOL_UNREACHABLE 2
#define ICMP_CODE_DESTINATION_PORT_UNREACHABLE 3
#define ICMP_CODE_FRAGMENTATION_REQUIRED 4
#define ICMP_CODE_SOURCE_ROUTE_FAILED 5
#define ICMP_CODE_DESTINATION_NETWORK_UNKNOWN 6
#define ICMP_CODE_DESTINATION_HOST_UNKNOWN 7
#define ICMP_CODE_SOURCE_HOST_ISOLATED 8
#define ICMP_CODE_NETWORK_ADMINISTRATIVELY_PROHIBITED 9
#define ICMP_CODE_HOST_ADMINISTRATIVELY_PROHIBITED 10
#define ICMP_CODE_NETWORK_UNREACHABLE 11
#define ICMP_CODE_HOST_UNREACHABLE 12
#define ICMP_CODE_COMMUNICATION_ADMINISTRATIVELY_PROHIBITED 13
#define ICMP_CODE_HOST_PRECEDENCE_VIOLATION 14
#define ICMP_CODE_PRECEDENCE_CUTOFF_IN_EFFECT 15
// Type 4 (ICMP_TYPE_SOURCE_QUENCH)
#define ICMP_CODE_SOURCE_QUENCH 0
// Type 5 (ICMP_TYPE_REDIRECT)
#define ICMP_CODE_REDIRECT_DATAGRAM_FOR_THE_NETWORK 0
#define ICMP_CODE_REDIRECT_DATAGRAM_FOR_THE_HOST 1
#define ICMP_CODE_REDIRECT_DATAGRAM_FOR_THE_TOS_AND_NETWORK 2
#define ICMP_CODE_REDIRECT_DATAGRAM_FOR_THE_TOS_AND_HOST 3
// Type 8 (ICMP_TYPE_ECHO_REQUEST)
#define ICMP_CODE_ECHO_REQUEST 0
// Type 9 (ICMP_TYPE_ROUTER_ADVERTISEMENT)
#define ICMP_CODE_ROUTER_ADVERTISEMENT 0
// Type 10 (ICMP_TYPE_ROUTER_SOLICITATION)
#define ICMP_CODE_ROUTER_DISCOVERY_SELECTION_SOLICITATION 0
// Type 11 (ICMP_TYPE_TIME_EXCEEDED)
#define ICMP_CODE_TLL_EXPIRED_IN_TRANSIT
// Type 12 (ICMP_TYPE_PARAMETER_PROBLEM)
#define ICMP_CODE_POINTER_INDICATES_THE_ERROR 0
#define ICMP_CODE_MISSING_A_REQUIRED_OPTION 1
#define ICMP_CODE_BAD_LENGTH 2
// Type 13 (ICMP_TYPE_TIMESTAMP)
#define ICMP_CODE_TIMESTAMP 0
// Type 14 ()
#define ICMP_CODE_TIMESTAMP_REPLY 0
// Type 15 () & Type 30 ()
#define ICMP_CODE_INFORMATION_REQUEST 0
// Type 16 ()
#define ICMP_CODE_INFORMATION_REPLY 0
// Type 17 ()
#define ICMP_CODE_ADDRESS_MASK_REQUEST 0
// Type 18 ()
#define ICMP_CODE_ADDRESS_MASK_REPLY 0

namespace nettools
{
    struct icmp_header
    {
        u8 m_type;
        u8 m_code;
        u16 m_checksum;

        u32 m_data_length;
        u8 *m_data;
    };

    u16 icmp_calculate_checksum(icmp_header *);
}